# Generated by Django 3.2 on 2021-05-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todosapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='TaskName',
            new_name='taskname',
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('notcompleted', 'notcompleted')], default='notcompleted', max_length=12),
        ),
    ]
